2023-04-23 08:03:28 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to get state
2023-04-23 08:03:28 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to set attempt sync config
2023-04-23 08:03:28 [32mINFO[m i.a.c.t.s.DefaultTaskQueueMapper(getTaskQueue):31 - Called DefaultTaskQueueMapper getTaskQueue for geography auto
2023-04-23 08:03:28 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):136 - Docker volume job log path: /tmp/workspace/1/0/logs.log
2023-04-23 08:03:28 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):141 - Executing worker wrapper. Airbyte version: 0.44.1
2023-04-23 08:03:28 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to save workflow id for cancellation
2023-04-23 08:03:28 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to get the source for heartbeat
2023-04-23 08:03:28 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to get the source definition
2023-04-23 08:03:28 [32mINFO[m i.a.w.g.ReplicationWorkerFactory(create):95 - Setting up source...
2023-04-23 08:03:28 [32mINFO[m i.a.w.g.ReplicationWorkerFactory(create):99 - Setting up destination...
2023-04-23 08:03:28 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable METRIC_CLIENT: ''
2023-04-23 08:03:28 [33mWARN[m i.a.m.l.MetricClientFactory(initialize):60 - Metric client is already initialized to 
2023-04-23 08:03:28 [32mINFO[m i.a.w.g.ReplicationWorkerFactory(create):108 - Setting up replication worker...
2023-04-23 08:03:28 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):278 - Unknown keyword example - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-04-23 08:03:28 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):278 - Unknown keyword existingJavaType - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-04-23 08:03:28 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):161 - start sync worker. job id: 1 attempt id: 0
2023-04-23 08:03:28 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):163 - Committing states from replication activity
2023-04-23 08:03:28 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):166 - Committing stats from replication activity
2023-04-23 08:03:28 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-23 08:03:28 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- START REPLICATION -----
2023-04-23 08:03:28 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-23 08:03:28 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):182 - configured sync modes: {null.api_data=full_refresh - overwrite}
2023-04-23 08:03:28 [32mINFO[m i.a.w.i.DefaultAirbyteDestination(start):92 - Running destination...
2023-04-23 08:03:28 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2023-04-23 08:03:28 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2023-04-23 08:03:28 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2023-04-23 08:03:28 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2023-04-23 08:03:28 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable LAUNCHDARKLY_KEY: ''
2023-04-23 08:03:28 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable FEATURE_FLAG_CLIENT: ''
2023-04-23 08:03:28 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - Checking if airbyte/destination-mysql:0.1.20 exists...
2023-04-23 08:03:28 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - airbyte/destination-mysql:0.1.20 was found locally.
2023-04-23 08:03:28 [32mINFO[m i.a.w.p.DockerProcessFactory(create):133 - Creating docker container = destination-mysql-write-1-0-aiqzf with resources io.airbyte.config.ResourceRequirements@59a663e3[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts null
2023-04-23 08:03:28 [32mINFO[m i.a.w.p.DockerProcessFactory(create):184 - Preparing command: docker run --rm --init -i -w /data/1/0 --log-driver none --name destination-mysql-write-1-0-aiqzf --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/destination-mysql:0.1.20 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e USE_STREAM_CAPABLE_STATE=true -e FIELD_SELECTION_WORKSPACES= -e WORKER_ENVIRONMENT=DOCKER -e AIRBYTE_ROLE= -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=0 -e OTEL_COLLECTOR_ENDPOINT=http://host.docker.internal:4317 -e FEATURE_FLAG_CLIENT= -e AIRBYTE_VERSION=0.44.1 -e WORKER_JOB_ID=1 airbyte/destination-mysql:0.1.20 write --config destination_config.json --catalog destination_catalog.json
2023-04-23 08:03:28 [32mINFO[m i.a.w.i.VersionedAirbyteMessageBufferedWriterFactory(createWriter):41 - Writing messages to protocol version 0.2.0
2023-04-23 08:03:28 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(create):181 - Reading messages from protocol version 0.2.0
2023-04-23 08:03:28 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2023-04-23 08:03:28 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2023-04-23 08:03:28 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2023-04-23 08:03:28 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2023-04-23 08:03:28 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable LAUNCHDARKLY_KEY: ''
2023-04-23 08:03:28 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable FEATURE_FLAG_CLIENT: ''
2023-04-23 08:03:28 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - Checking if airbyte/source-customize-api:0.0.12 exists...
2023-04-23 08:03:28 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - airbyte/source-customize-api:0.0.12 was found locally.
2023-04-23 08:03:28 [32mINFO[m i.a.w.p.DockerProcessFactory(create):133 - Creating docker container = source-customize-api-read-1-0-ieujl with resources io.airbyte.config.ResourceRequirements@6e225a4f[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts null
2023-04-23 08:03:28 [32mINFO[m i.a.w.p.DockerProcessFactory(create):184 - Preparing command: docker run --rm --init -i -w /data/1/0 --log-driver none --name source-customize-api-read-1-0-ieujl --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/source-customize-api:0.0.12 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e USE_STREAM_CAPABLE_STATE=true -e FIELD_SELECTION_WORKSPACES= -e WORKER_ENVIRONMENT=DOCKER -e AIRBYTE_ROLE= -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=0 -e OTEL_COLLECTOR_ENDPOINT=http://host.docker.internal:4317 -e FEATURE_FLAG_CLIENT= -e AIRBYTE_VERSION=0.44.1 -e WORKER_JOB_ID=1 airbyte/source-customize-api:0.0.12 read --config source_config.json --catalog source_catalog.json
2023-04-23 08:03:28 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(create):181 - Reading messages from protocol version 0.2.0
2023-04-23 08:03:28 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$readFromDstRunnable$4):310 - Destination output thread started.
2023-04-23 08:03:28 [32mINFO[m i.a.w.i.HeartbeatTimeoutChaperone(runWithHeartbeatThread):94 - Starting source heartbeat check. Will check every 1 minutes.
2023-04-23 08:03:28 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$readFromSrcAndWriteToDstRunnable$8):376 - Replication thread started.
2023-04-23 08:03:29 [43mdestination[0m > SLF4J: Class path contains multiple SLF4J bindings.
2023-04-23 08:03:29 [43mdestination[0m > SLF4J: Found binding in [jar:file:/airbyte/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-04-23 08:03:29 [43mdestination[0m > SLF4J: Found binding in [jar:file:/airbyte/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-04-23 08:03:29 [43mdestination[0m > SLF4J: Found binding in [jar:file:/airbyte/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-04-23 08:03:29 [43mdestination[0m > SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
2023-04-23 08:03:29 [43mdestination[0m > SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
2023-04-23 08:03:29 [44msource[0m > Starting syncing SourceCustomizeAPI
2023-04-23 08:03:29 [43mdestination[0m > 2023-04-23 08:03:29 [32mINFO[m i.a.i.d.m.MySQLDestination(main):136 - starting destination: class io.airbyte.integrations.destination.mysql.MySQLDestination
2023-04-23 08:03:29 [43mdestination[0m > 2023-04-23 08:03:29 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):118 - integration args: {catalog=destination_catalog.json, write=null, config=destination_config.json}
2023-04-23 08:03:29 [43mdestination[0m > 2023-04-23 08:03:29 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):123 - Running integration: io.airbyte.integrations.base.ssh.SshWrappedDestination
2023-04-23 08:03:29 [43mdestination[0m > 2023-04-23 08:03:29 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):124 - Command: WRITE
2023-04-23 08:03:29 [43mdestination[0m > 2023-04-23 08:03:29 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):125 - Integration config: IntegrationConfig{command=WRITE, configPath='destination_config.json', catalogPath='destination_catalog.json', statePath='null'}
2023-04-23 08:03:30 [43mdestination[0m > 2023-04-23 08:03:30 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-04-23 08:03:30 [43mdestination[0m > 2023-04-23 08:03:30 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword examples - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-04-23 08:03:30 [43mdestination[0m > 2023-04-23 08:03:30 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-04-23 08:03:30 [43mdestination[0m > 2023-04-23 08:03:30 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword multiline - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-04-23 08:03:30 [43mdestination[0m > 2023-04-23 08:03:30 [32mINFO[m i.a.i.b.s.SshTunnel(getInstance):170 - Starting connection with method: NO_TUNNEL
2023-04-23 08:03:30 [43mdestination[0m > 2023-04-23 08:03:30 [32mINFO[m c.z.h.HikariDataSource(<init>):80 - HikariPool-1 - Starting...
2023-04-23 08:03:30 [43mdestination[0m > 2023-04-23 08:03:30 [32mINFO[m c.z.h.HikariDataSource(<init>):82 - HikariPool-1 - Start completed.
2023-04-23 08:03:30 [43mdestination[0m > 2023-04-23 08:03:30 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):98 - Write config: WriteConfig{streamName=api_data, namespace=null, outputSchemaName=api, tmpTableName=_airbyte_tmp_nlo_api_data, outputTableName=_airbyte_raw_api_data, syncMode=overwrite}
2023-04-23 08:03:30 [43mdestination[0m > 2023-04-23 08:03:30 [32mINFO[m i.a.i.d.b.BufferedStreamConsumer(startTracked):116 - class io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer started.
2023-04-23 08:03:30 [43mdestination[0m > 2023-04-23 08:03:30 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):123 - Preparing tmp tables in destination started for 1 streams
2023-04-23 08:03:30 [43mdestination[0m > 2023-04-23 08:03:30 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):127 - Preparing tmp table in destination started for stream api_data. schema: api, tmp table name: _airbyte_tmp_nlo_api_data
2023-04-23 08:03:30 [43mdestination[0m > 2023-04-23 08:03:30 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):133 - Preparing tables in destination completed.
2023-04-23 08:03:30 [44msource[0m > Syncing stream: api_data 
2023-04-23 08:03:32 [44msource[0m > Encountered an exception while reading stream api_data
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 116, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 185, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 304, in _read_full_refresh
    message = self._get_message(record_data_or_message, stream_instance)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 338, in _get_message
    return stream_data_to_airbyte_message(stream.name, record_data_or_message, stream.transformer, stream.get_json_schema())
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/record_helper.py", line 38, in stream_data_to_airbyte_message
    raise ValueError(f"Unexpected type for data_or_message: {type(data_or_message)}: {data_or_message}")
ValueError: Unexpected type for data_or_message: <class 'str'>: offset
2023-04-23 08:03:32 [44msource[0m > Finished syncing api_data
2023-04-23 08:03:32 [44msource[0m > SourceCustomizeAPI runtimes:
Syncing stream api_data 0:00:01.880137
2023-04-23 08:03:32 [44msource[0m > Unexpected type for data_or_message: <class 'str'>: offset
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 131, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 122, in run
    for message in generator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 130, in read
    raise e
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 116, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 185, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 304, in _read_full_refresh
    message = self._get_message(record_data_or_message, stream_instance)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 338, in _get_message
    return stream_data_to_airbyte_message(stream.name, record_data_or_message, stream.transformer, stream.get_json_schema())
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/record_helper.py", line 38, in stream_data_to_airbyte_message
    raise ValueError(f"Unexpected type for data_or_message: {type(data_or_message)}: {data_or_message}")
ValueError: Unexpected type for data_or_message: <class 'str'>: offset
2023-04-23 08:03:32 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$readFromSrcAndWriteToDstRunnable$8):438 - Source has no more messages, closing connection.
2023-04-23 08:03:32 [43mdestination[0m > 2023-04-23 08:03:32 [32mINFO[m i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):65 - Airbyte message consumer: succeeded.
2023-04-23 08:03:32 [43mdestination[0m > 2023-04-23 08:03:32 [32mINFO[m i.a.i.d.b.BufferedStreamConsumer(close):171 - executing on success close procedure.
2023-04-23 08:03:32 [43mdestination[0m > 2023-04-23 08:03:32 [32mINFO[m i.a.i.d.j.SqlOperations(onDestinationCloseOperations):138 - No onDestinationCloseOperations required for this destination.
2023-04-23 08:03:32 [43mdestination[0m > 2023-04-23 08:03:32 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):163 - Finalizing tables in destination started for 1 streams
2023-04-23 08:03:32 [43mdestination[0m > 2023-04-23 08:03:32 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):168 - Finalizing stream api_data. schema api, tmp table _airbyte_tmp_nlo_api_data, final table _airbyte_raw_api_data
2023-04-23 08:03:32 [43mdestination[0m > 2023-04-23 08:03:32 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):181 - Executing finalization of tables.
2023-04-23 08:03:32 [43mdestination[0m > 2023-04-23 08:03:32 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):183 - Finalizing tables in destination completed.
2023-04-23 08:03:32 [43mdestination[0m > 2023-04-23 08:03:32 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):186 - Cleaning tmp tables in destination started for 1 streams
2023-04-23 08:03:32 [43mdestination[0m > 2023-04-23 08:03:32 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):190 - Cleaning tmp table in destination started for stream api_data. schema api, tmp table name: _airbyte_tmp_nlo_api_data
2023-04-23 08:03:32 [43mdestination[0m > 2023-04-23 08:03:32 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):195 - Cleaning tmp tables in destination completed.
2023-04-23 08:03:32 [43mdestination[0m > 2023-04-23 08:03:32 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):171 - Completed integration: io.airbyte.integrations.base.ssh.SshWrappedDestination
2023-04-23 08:03:32 [43mdestination[0m > 2023-04-23 08:03:32 [32mINFO[m i.a.i.d.m.MySQLDestination(main):138 - completed destination: class io.airbyte.integrations.destination.mysql.MySQLDestination
2023-04-23 08:03:33 [1;31mERROR[m i.a.w.g.DefaultReplicationWorker(replicate):278 - Sync worker failed.
io.airbyte.workers.internal.exception.SourceException: Source didn't exit properly - check the logs!
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:442) ~[io.airbyte-airbyte-commons-worker-0.44.1.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
	Suppressed: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
		at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:150) ~[io.airbyte-airbyte-commons-worker-0.44.1.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.replicate(DefaultReplicationWorker.java:214) ~[io.airbyte-airbyte-commons-worker-0.44.1.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:190) ~[io.airbyte-airbyte-commons-worker-0.44.1.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:91) ~[io.airbyte-airbyte-commons-worker-0.44.1.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$5(TemporalAttemptExecution.java:195) ~[io.airbyte-airbyte-workers-0.44.1.jar:?]
		at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
	at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:150) ~[io.airbyte-airbyte-commons-worker-0.44.1.jar:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:440) ~[io.airbyte-airbyte-commons-worker-0.44.1.jar:?]
	... 4 more
2023-04-23 08:03:33 [32mINFO[m i.a.w.g.DefaultReplicationWorker(getReplicationOutput):561 - sync summary: {
  "status" : "failed",
  "recordsSynced" : 0,
  "bytesSynced" : 0,
  "startTime" : 1682237008746,
  "endTime" : 1682237013071,
  "totalStats" : {
    "bytesCommitted" : 0,
    "bytesEmitted" : 0,
    "destinationStateMessagesEmitted" : 0,
    "destinationWriteEndTime" : 1682237013049,
    "destinationWriteStartTime" : 1682237008859,
    "meanSecondsBeforeSourceStateMessageEmitted" : 0,
    "maxSecondsBeforeSourceStateMessageEmitted" : 0,
    "maxSecondsBetweenStateMessageEmittedandCommitted" : 0,
    "meanSecondsBetweenStateMessageEmittedandCommitted" : 0,
    "recordsEmitted" : 0,
    "recordsCommitted" : 0,
    "replicationEndTime" : 1682237013065,
    "replicationStartTime" : 1682237008746,
    "sourceReadEndTime" : 0,
    "sourceReadStartTime" : 1682237008805,
    "sourceStateMessagesEmitted" : 0
  },
  "streamStats" : [ ]
}
2023-04-23 08:03:33 [32mINFO[m i.a.w.g.DefaultReplicationWorker(getReplicationOutput):562 - failures: [ {
  "failureOrigin" : "source",
  "failureType" : "system_error",
  "internalMessage" : "Unexpected type for data_or_message: <class 'str'>: offset",
  "externalMessage" : "Something went wrong in the connector. See the logs for more details.",
  "metadata" : {
    "attemptNumber" : 0,
    "jobId" : 1,
    "from_trace_message" : true,
    "connector_command" : "read"
  },
  "stacktrace" : "Traceback (most recent call last):\n  File \"/airbyte/integration_code/main.py\", line 13, in <module>\n    launch(source, sys.argv[1:])\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\", line 131, in launch\n    for message in source_entrypoint.run(parsed_args):\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\", line 122, in run\n    for message in generator:\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 130, in read\n    raise e\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 116, in read\n    yield from self._read_stream(\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 185, in _read_stream\n    for record in record_iterator:\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 304, in _read_full_refresh\n    message = self._get_message(record_data_or_message, stream_instance)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 338, in _get_message\n    return stream_data_to_airbyte_message(stream.name, record_data_or_message, stream.transformer, stream.get_json_schema())\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/record_helper.py\", line 38, in stream_data_to_airbyte_message\n    raise ValueError(f\"Unexpected type for data_or_message: {type(data_or_message)}: {data_or_message}\")\nValueError: Unexpected type for data_or_message: <class 'str'>: offset\n",
  "timestamp" : 1682237012678
}, {
  "failureOrigin" : "source",
  "internalMessage" : "Source didn't exit properly - check the logs!",
  "externalMessage" : "Something went wrong within the source connector",
  "metadata" : {
    "attemptNumber" : 0,
    "jobId" : 1,
    "connector_command" : "read"
  },
  "stacktrace" : "io.airbyte.workers.internal.exception.SourceException: Source didn't exit properly - check the logs!\n\tat io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:442)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1589)\nCaused by: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.\n\tat io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:150)\n\tat io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:440)\n\t... 4 more\n",
  "timestamp" : 1682237012862
} ]
2023-04-23 08:03:33 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):163 - Stopping cancellation check scheduling...
2023-04-23 08:03:33 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-23 08:03:33 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- END REPLICATION -----
2023-04-23 08:03:33 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-23 08:03:33 [32mINFO[m i.a.w.t.s.ReplicationActivityImpl(lambda$replicate$3):157 - sync summary: io.airbyte.config.StandardSyncOutput@2331d8a8[standardSyncSummary=io.airbyte.config.StandardSyncSummary@7c51c06b[status=failed,recordsSynced=0,bytesSynced=0,startTime=1682237008746,endTime=1682237013071,totalStats=io.airbyte.config.SyncStats@6074bda1[bytesCommitted=0,bytesEmitted=0,destinationStateMessagesEmitted=0,destinationWriteEndTime=1682237013049,destinationWriteStartTime=1682237008859,estimatedBytes=<null>,estimatedRecords=<null>,meanSecondsBeforeSourceStateMessageEmitted=0,maxSecondsBeforeSourceStateMessageEmitted=0,maxSecondsBetweenStateMessageEmittedandCommitted=0,meanSecondsBetweenStateMessageEmittedandCommitted=0,recordsEmitted=0,recordsCommitted=0,replicationEndTime=1682237013065,replicationStartTime=1682237008746,sourceReadEndTime=0,sourceReadStartTime=1682237008805,sourceStateMessagesEmitted=0,additionalProperties={}],streamStats=[],additionalProperties={}],normalizationSummary=<null>,webhookOperationSummary=<null>,state=<null>,outputCatalog=io.airbyte.protocol.models.ConfiguredAirbyteCatalog@6b5083a3[streams=[io.airbyte.protocol.models.ConfiguredAirbyteStream@4609f2f9[stream=io.airbyte.protocol.models.AirbyteStream@34a930cb[name=api_data,jsonSchema={"$schema":"http://json-schema.org/draft-07/schema","type":"object","required":["url"],"properties":{"headers":{"description":"The headers for the API request, it is a json format,eg:{'Authorization':'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ1aWQi……'}","type":"object"},"http_method":{"description":"HTTP request method, the default is GET..","type":"string"},"url":{"description":"The URL for the API endpoint.","type":"string"}}},supportedSyncModes=[full_refresh],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=overwrite,primaryKey=[],additionalProperties={}]],additionalProperties={}],failures=[io.airbyte.config.FailureReason@6cbb3187[failureOrigin=source,failureType=system_error,internalMessage=Unexpected type for data_or_message: <class 'str'>: offset,externalMessage=Something went wrong in the connector. See the logs for more details.,metadata=io.airbyte.config.Metadata@58d38c83[additionalProperties={attemptNumber=0, jobId=1, from_trace_message=true, connector_command=read}],stacktrace=Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 131, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 122, in run
    for message in generator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 130, in read
    raise e
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 116, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 185, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 304, in _read_full_refresh
    message = self._get_message(record_data_or_message, stream_instance)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 338, in _get_message
    return stream_data_to_airbyte_message(stream.name, record_data_or_message, stream.transformer, stream.get_json_schema())
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/record_helper.py", line 38, in stream_data_to_airbyte_message
    raise ValueError(f"Unexpected type for data_or_message: {type(data_or_message)}: {data_or_message}")
ValueError: Unexpected type for data_or_message: <class 'str'>: offset
,retryable=<null>,timestamp=1682237012678,additionalProperties={}], io.airbyte.config.FailureReason@6e21d59f[failureOrigin=source,failureType=<null>,internalMessage=Source didn't exit properly - check the logs!,externalMessage=Something went wrong within the source connector,metadata=io.airbyte.config.Metadata@4eaac48e[additionalProperties={attemptNumber=0, jobId=1, connector_command=read}],stacktrace=io.airbyte.workers.internal.exception.SourceException: Source didn't exit properly - check the logs!
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:442)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
	at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:150)
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:440)
	... 4 more
,retryable=<null>,timestamp=1682237012862,additionalProperties={}]],commitStateAsap=true,additionalProperties={}]
2023-04-23 08:03:33 [32mINFO[m i.a.w.t.s.ReplicationActivityImpl(lambda$replicate$3):162 - Sync summary length: 5334
2023-04-23 08:03:33 [32mINFO[m i.a.c.t.TemporalUtils(withBackgroundHeartbeat):307 - Stopping temporal heartbeating...
2023-04-23 08:03:37 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to Get a connection by connection Id
2023-04-23 08:03:37 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to get the most recent source actor catalog
2023-04-23 08:03:37 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to Get a connection by connection Id
2023-04-23 08:03:33 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):136 - Docker volume job log path: /tmp/workspace/1/1/logs.log
2023-04-23 08:03:33 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):141 - Executing worker wrapper. Airbyte version: 0.44.1
2023-04-23 08:03:33 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to save workflow id for cancellation
2023-04-23 08:03:33 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2023-04-23 08:03:33 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-23 08:03:33 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- START CHECK -----
2023-04-23 08:03:33 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-23 08:03:33 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2023-04-23 08:03:33 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2023-04-23 08:03:33 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2023-04-23 08:03:33 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable LAUNCHDARKLY_KEY: ''
2023-04-23 08:03:33 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable FEATURE_FLAG_CLIENT: ''
2023-04-23 08:03:33 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - Checking if airbyte/source-customize-api:0.0.12 exists...
2023-04-23 08:03:33 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - airbyte/source-customize-api:0.0.12 was found locally.
2023-04-23 08:03:33 [32mINFO[m i.a.w.p.DockerProcessFactory(create):133 - Creating docker container = source-customize-api-check-1-1-tszus with resources io.airbyte.config.ResourceRequirements@9e89d38[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts null
2023-04-23 08:03:33 [32mINFO[m i.a.w.p.DockerProcessFactory(create):184 - Preparing command: docker run --rm --init -i -w /data/1/1 --log-driver none --name source-customize-api-check-1-1-tszus --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/source-customize-api:0.0.12 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e USE_STREAM_CAPABLE_STATE=true -e FIELD_SELECTION_WORKSPACES= -e WORKER_ENVIRONMENT=DOCKER -e AIRBYTE_ROLE= -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=1 -e OTEL_COLLECTOR_ENDPOINT=http://host.docker.internal:4317 -e FEATURE_FLAG_CLIENT= -e AIRBYTE_VERSION=0.44.1 -e WORKER_JOB_ID=1 airbyte/source-customize-api:0.0.12 check --config source_config.json
2023-04-23 08:03:33 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(create):181 - Reading messages from protocol version 0.2.0
2023-04-23 08:03:34 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):317 - headers_str: { 	"Authorization": "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJTNmJDSFdHU3p1VjgtaVFZY19OdE9yUUpick54RDF2dEV4U0duOXMtMnRRIn0.eyJqdGkiOiIxN2EwY2UyMi00ZjM4LTRhOWYtODExNy1hNWZkOGVjOWZjYWQiLCJleHAiOjE2ODIzMjA3OTMsIm5iZiI6MCwiaWF0IjoxNjgyMjM0MzkzLCJpc3MiOiJodHRwczovL2JvLXRlc3Qtc3NvLmxpbmt0aW1lY2xvdWQuY29tL2F1dGgvcmVhbG1zL2Jkb3MiLCJzdWIiOiJiNGZhZjY1Yi1hNmMwLTQ2ZTEtYTYyNy1lYzJlMjU3OWZjZTciLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiZG9zLWV0bCIsImF1dGhfdGltZSI6MCwic2Vzc2lvbl9zdGF0ZSI6IjdlOWJlMmZjLTllZDQtNGFhNi1iOTMzLTBmYzVmNjhjNjY0NSIsImFjciI6IjEiLCJzY29wZSI6InByb2ZpbGUgZW1haWwiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJicmFuZG9uIGJkb3MiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJicmFuZG9uIiwiZ2l2ZW5fbmFtZSI6ImJyYW5kb24iLCJsb2NhbGUiOiJ6aC1DTiIsImZhbWlseV9uYW1lIjoiYmRvcyIsImVtYWlsIjoiYnJhbmRvbi5zdW5AbGlua3RpbWUuY2xvdWQifQ.P4iBqSIDbjv8yN7kbyGdEobQ2LWMcznMiGT-qA0hlFcd0gulN-mLal5TgBe4HQIbtGuQX1xU6M21GznAm6ZpZIyyA4YFBVnzgtkpG3V12aKotEgScgCPwgkGAj0Q4wuPoKDA6I2VMA0IzTBdP9h4ibPrb5n4n-44zm8K1JcoSl_PLC60A9ztWEEVfSpAF4lZlWINg44-ComenW5c-p7rL1nHGKmvnxlweXqFnlzZccyDFRCFWbRDr1OT7u0w2nGjme6bBqA1QEE2p-Sdq0ozNZlZ_dZFpIeCWFrar7GLvU8sYB5xp2jJFcrLibl3v_OiX6QKKeLfVT1QNsxUpiYlXA", 	"active-org": "uid=fda805d0-ba2b-11ec-b905-51d902e7b1bc;user=brandon;reqUserName=brandon;type=undefined" }...
2023-04-23 08:03:34 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):317 - body_data: {'limit': 2, 'loginUserName': 'brandon', 'user': 'brandon'}...
2023-04-23 08:03:34 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):317 - Attempting to connect to API at http://192.168.200.124:9099/project/list...
2023-04-23 08:03:34 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):317 - http method is-> POST...
2023-04-23 08:03:35 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):317 - Response from POST: http://192.168.200.124:9099/project/list: {'message': 'success', 'status': 1, 'data': {'offset': 0, 'limit': None, 'total': 74, 'list': [{'id': 2860, 'status': 0, 'sourceProjectId': None, 'name': 'python导出test_模板_1680589641748', 'desc': '', 'homepageUrl': None, 'homepageName': None, 'homepageImg': None, 'readme': None, 'openFlag': '{"tutorial":false}', 'type': 3, 'userId': 'brandon', 'groupId': '0a71e4b0-c3a1-11ec-96bd-35126eddec60', 'workflowId': None, 'cron': None, 'avatar': None, 'features': None, 'lastClickTime': '2023-04-19 14:21:05', 'createTime': '2023-04-04 14:27:24', 'updateTime': '2023-04-18 12:58:42', 'memberIds': [], 'groupIds': [], 'tags': None, 'updateUserId': 'brandon', 'starCount': 0, 'categoryId': 1, 'secondaryCategoryId': 0}, {'id': 2857, 'status': 0, 'sourceProjectId': None, 'name': 'python导出test', 'desc': '', 'homepageUrl': None, 'homepageName': None, 'homepageImg': None, 'readme': None, 'openFlag': None, 'type': 4, 'userId': 'qa25org_admin', 'groupId': '0a71e4b0-c3a1-11ec-96bd-35126eddec60', 'workflowId': None, 'cron': None, 'avatar': None, 'features': None, 'lastClickTime': '2023-04-04 09:25:57', 'createTime': '2023-04-04 09:21:42', 'updateTime': '2023-04-04 09:26:19', 'memberIds': [], 'groupIds': [], 'tags': None, 'updateUserId': 'qa25org_admin', 'starCount': 0, 'categoryId': 1, 'secondaryCategoryId': 0}]}, 'error': None}
2023-04-23 08:03:35 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):317 - Check connection status: True
2023-04-23 08:03:35 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):317 - Check connection success
2023-04-23 08:03:35 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):317 - Check succeeded
2023-04-23 08:03:35 [32mINFO[m i.a.w.g.DefaultCheckConnectionWorker(run):115 - Check connection job received output: io.airbyte.config.StandardCheckConnectionOutput@70f656da[status=succeeded,message=<null>,additionalProperties={}]
2023-04-23 08:03:35 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):163 - Stopping cancellation check scheduling...
2023-04-23 08:03:35 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-23 08:03:35 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- END CHECK -----
2023-04-23 08:03:35 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-23 08:03:35 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):136 - Docker volume job log path: /tmp/workspace/1/1/logs.log
2023-04-23 08:03:35 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):141 - Executing worker wrapper. Airbyte version: 0.44.1
2023-04-23 08:03:35 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to save workflow id for cancellation
2023-04-23 08:03:35 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2023-04-23 08:03:35 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-23 08:03:35 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2023-04-23 08:03:35 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- START CHECK -----
2023-04-23 08:03:35 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-23 08:03:35 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2023-04-23 08:03:35 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2023-04-23 08:03:35 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable LAUNCHDARKLY_KEY: ''
2023-04-23 08:03:35 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable FEATURE_FLAG_CLIENT: ''
2023-04-23 08:03:35 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - Checking if airbyte/destination-mysql:0.1.20 exists...
2023-04-23 08:03:35 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - airbyte/destination-mysql:0.1.20 was found locally.
2023-04-23 08:03:35 [32mINFO[m i.a.w.p.DockerProcessFactory(create):133 - Creating docker container = destination-mysql-check-1-1-cuhhe with resources io.airbyte.config.ResourceRequirements@9e89d38[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts null
2023-04-23 08:03:35 [32mINFO[m i.a.w.p.DockerProcessFactory(create):184 - Preparing command: docker run --rm --init -i -w /data/1/1 --log-driver none --name destination-mysql-check-1-1-cuhhe --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/destination-mysql:0.1.20 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e USE_STREAM_CAPABLE_STATE=true -e FIELD_SELECTION_WORKSPACES= -e WORKER_ENVIRONMENT=DOCKER -e AIRBYTE_ROLE= -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=1 -e OTEL_COLLECTOR_ENDPOINT=http://host.docker.internal:4317 -e FEATURE_FLAG_CLIENT= -e AIRBYTE_VERSION=0.44.1 -e WORKER_JOB_ID=1 airbyte/destination-mysql:0.1.20 check --config source_config.json
2023-04-23 08:03:35 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(create):181 - Reading messages from protocol version 0.2.0
2023-04-23 08:03:35 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):149 - SLF4J: Class path contains multiple SLF4J bindings.
2023-04-23 08:03:35 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):149 - SLF4J: Found binding in [jar:file:/airbyte/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-04-23 08:03:35 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):149 - SLF4J: Found binding in [jar:file:/airbyte/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-04-23 08:03:35 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):149 - SLF4J: Found binding in [jar:file:/airbyte/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-04-23 08:03:35 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):149 - SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
2023-04-23 08:03:36 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):149 - SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
2023-04-23 08:03:36 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:36 [32mINFO[m i.a.i.d.m.MySQLDestination(main):136 - starting destination: class io.airbyte.integrations.destination.mysql.MySQLDestination
2023-04-23 08:03:36 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:36 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):118 - integration args: {check=null, config=source_config.json}
2023-04-23 08:03:36 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:36 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):123 - Running integration: io.airbyte.integrations.base.ssh.SshWrappedDestination
2023-04-23 08:03:36 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:36 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):124 - Command: CHECK
2023-04-23 08:03:36 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:36 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):125 - Integration config: IntegrationConfig{command=CHECK, configPath='source_config.json', catalogPath='null', statePath='null'}
2023-04-23 08:03:36 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:36 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-04-23 08:03:36 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:36 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword examples - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-04-23 08:03:36 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:36 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-04-23 08:03:36 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:36 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword multiline - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-04-23 08:03:36 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:36 [32mINFO[m i.a.i.b.s.SshTunnel(getInstance):170 - Starting connection with method: NO_TUNNEL
2023-04-23 08:03:36 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:36 [32mINFO[m c.z.h.HikariDataSource(<init>):80 - HikariPool-1 - Starting...
2023-04-23 08:03:36 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:36 [32mINFO[m c.z.h.HikariDataSource(<init>):82 - HikariPool-1 - Start completed.
2023-04-23 08:03:37 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:37 [32mINFO[m c.z.h.HikariDataSource(close):350 - HikariPool-1 - Shutdown initiated...
2023-04-23 08:03:37 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:37 [32mINFO[m c.z.h.HikariDataSource(close):352 - HikariPool-1 - Shutdown completed.
2023-04-23 08:03:37 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:37 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):171 - Completed integration: io.airbyte.integrations.base.ssh.SshWrappedDestination
2023-04-23 08:03:37 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:37 [32mINFO[m i.a.i.d.m.MySQLDestination(main):138 - completed destination: class io.airbyte.integrations.destination.mysql.MySQLDestination
2023-04-23 08:03:37 [32mINFO[m i.a.w.g.DefaultCheckConnectionWorker(run):115 - Check connection job received output: io.airbyte.config.StandardCheckConnectionOutput@44108cd0[status=succeeded,message=<null>,additionalProperties={}]
2023-04-23 08:03:37 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):163 - Stopping cancellation check scheduling...
2023-04-23 08:03:37 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-23 08:03:37 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- END CHECK -----
2023-04-23 08:03:37 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-23 08:03:37 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to get state
2023-04-23 08:03:37 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to set attempt sync config
2023-04-23 08:03:37 [32mINFO[m i.a.c.t.s.DefaultTaskQueueMapper(getTaskQueue):31 - Called DefaultTaskQueueMapper getTaskQueue for geography auto
2023-04-23 08:03:37 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):136 - Docker volume job log path: /tmp/workspace/1/1/logs.log
2023-04-23 08:03:37 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):141 - Executing worker wrapper. Airbyte version: 0.44.1
2023-04-23 08:03:37 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to save workflow id for cancellation
2023-04-23 08:03:37 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to get the source for heartbeat
2023-04-23 08:03:37 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to get the source definition
2023-04-23 08:03:37 [32mINFO[m i.a.w.g.ReplicationWorkerFactory(create):95 - Setting up source...
2023-04-23 08:03:37 [32mINFO[m i.a.w.g.ReplicationWorkerFactory(create):99 - Setting up destination...
2023-04-23 08:03:37 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable METRIC_CLIENT: ''
2023-04-23 08:03:37 [33mWARN[m i.a.m.l.MetricClientFactory(initialize):60 - Metric client is already initialized to 
2023-04-23 08:03:37 [32mINFO[m i.a.w.g.ReplicationWorkerFactory(create):108 - Setting up replication worker...
2023-04-23 08:03:37 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):161 - start sync worker. job id: 1 attempt id: 1
2023-04-23 08:03:37 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):163 - Committing states from replication activity
2023-04-23 08:03:37 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):166 - Committing stats from replication activity
2023-04-23 08:03:37 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):182 - configured sync modes: {null.api_data=full_refresh - overwrite}
2023-04-23 08:03:37 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-23 08:03:37 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- START REPLICATION -----
2023-04-23 08:03:37 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-23 08:03:37 [32mINFO[m i.a.w.i.DefaultAirbyteDestination(start):92 - Running destination...
2023-04-23 08:03:37 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2023-04-23 08:03:37 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2023-04-23 08:03:37 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2023-04-23 08:03:37 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2023-04-23 08:03:37 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable LAUNCHDARKLY_KEY: ''
2023-04-23 08:03:37 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable FEATURE_FLAG_CLIENT: ''
2023-04-23 08:03:37 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - Checking if airbyte/destination-mysql:0.1.20 exists...
2023-04-23 08:03:37 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - airbyte/destination-mysql:0.1.20 was found locally.
2023-04-23 08:03:37 [32mINFO[m i.a.w.p.DockerProcessFactory(create):133 - Creating docker container = destination-mysql-write-1-1-muhlm with resources io.airbyte.config.ResourceRequirements@51f0f7ce[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts null
2023-04-23 08:03:37 [32mINFO[m i.a.w.p.DockerProcessFactory(create):184 - Preparing command: docker run --rm --init -i -w /data/1/1 --log-driver none --name destination-mysql-write-1-1-muhlm --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/destination-mysql:0.1.20 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e USE_STREAM_CAPABLE_STATE=true -e FIELD_SELECTION_WORKSPACES= -e WORKER_ENVIRONMENT=DOCKER -e AIRBYTE_ROLE= -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=1 -e OTEL_COLLECTOR_ENDPOINT=http://host.docker.internal:4317 -e FEATURE_FLAG_CLIENT= -e AIRBYTE_VERSION=0.44.1 -e WORKER_JOB_ID=1 airbyte/destination-mysql:0.1.20 write --config destination_config.json --catalog destination_catalog.json
2023-04-23 08:03:37 [32mINFO[m i.a.w.i.VersionedAirbyteMessageBufferedWriterFactory(createWriter):41 - Writing messages to protocol version 0.2.0
2023-04-23 08:03:37 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(create):181 - Reading messages from protocol version 0.2.0
2023-04-23 08:03:37 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2023-04-23 08:03:37 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2023-04-23 08:03:37 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2023-04-23 08:03:37 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2023-04-23 08:03:37 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable LAUNCHDARKLY_KEY: ''
2023-04-23 08:03:37 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable FEATURE_FLAG_CLIENT: ''
2023-04-23 08:03:37 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - Checking if airbyte/source-customize-api:0.0.12 exists...
2023-04-23 08:03:37 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - airbyte/source-customize-api:0.0.12 was found locally.
2023-04-23 08:03:37 [32mINFO[m i.a.w.p.DockerProcessFactory(create):133 - Creating docker container = source-customize-api-read-1-1-fwqts with resources io.airbyte.config.ResourceRequirements@449f4ad7[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts null
2023-04-23 08:03:37 [32mINFO[m i.a.w.p.DockerProcessFactory(create):184 - Preparing command: docker run --rm --init -i -w /data/1/1 --log-driver none --name source-customize-api-read-1-1-fwqts --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/source-customize-api:0.0.12 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e USE_STREAM_CAPABLE_STATE=true -e FIELD_SELECTION_WORKSPACES= -e WORKER_ENVIRONMENT=DOCKER -e AIRBYTE_ROLE= -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=1 -e OTEL_COLLECTOR_ENDPOINT=http://host.docker.internal:4317 -e FEATURE_FLAG_CLIENT= -e AIRBYTE_VERSION=0.44.1 -e WORKER_JOB_ID=1 airbyte/source-customize-api:0.0.12 read --config source_config.json --catalog source_catalog.json
2023-04-23 08:03:37 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(create):181 - Reading messages from protocol version 0.2.0
2023-04-23 08:03:37 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$readFromDstRunnable$4):310 - Destination output thread started.
2023-04-23 08:03:37 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$readFromSrcAndWriteToDstRunnable$8):376 - Replication thread started.
2023-04-23 08:03:37 [32mINFO[m i.a.w.i.HeartbeatTimeoutChaperone(runWithHeartbeatThread):94 - Starting source heartbeat check. Will check every 1 minutes.
2023-04-23 08:03:37 [43mdestination[0m > SLF4J: Class path contains multiple SLF4J bindings.
2023-04-23 08:03:38 [43mdestination[0m > SLF4J: Found binding in [jar:file:/airbyte/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-04-23 08:03:38 [43mdestination[0m > SLF4J: Found binding in [jar:file:/airbyte/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-04-23 08:03:38 [43mdestination[0m > SLF4J: Found binding in [jar:file:/airbyte/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-04-23 08:03:38 [43mdestination[0m > SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
2023-04-23 08:03:38 [43mdestination[0m > SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
2023-04-23 08:03:38 [43mdestination[0m > 2023-04-23 08:03:38 [32mINFO[m i.a.i.d.m.MySQLDestination(main):136 - starting destination: class io.airbyte.integrations.destination.mysql.MySQLDestination
2023-04-23 08:03:38 [43mdestination[0m > 2023-04-23 08:03:38 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):118 - integration args: {catalog=destination_catalog.json, write=null, config=destination_config.json}
2023-04-23 08:03:38 [43mdestination[0m > 2023-04-23 08:03:38 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):123 - Running integration: io.airbyte.integrations.base.ssh.SshWrappedDestination
2023-04-23 08:03:38 [43mdestination[0m > 2023-04-23 08:03:38 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):124 - Command: WRITE
2023-04-23 08:03:38 [43mdestination[0m > 2023-04-23 08:03:38 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):125 - Integration config: IntegrationConfig{command=WRITE, configPath='destination_config.json', catalogPath='destination_catalog.json', statePath='null'}
2023-04-23 08:03:38 [43mdestination[0m > 2023-04-23 08:03:38 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-04-23 08:03:38 [43mdestination[0m > 2023-04-23 08:03:38 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword examples - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-04-23 08:03:38 [43mdestination[0m > 2023-04-23 08:03:38 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-04-23 08:03:38 [43mdestination[0m > 2023-04-23 08:03:38 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword multiline - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-04-23 08:03:38 [44msource[0m > Starting syncing SourceCustomizeAPI
2023-04-23 08:03:38 [43mdestination[0m > 2023-04-23 08:03:38 [32mINFO[m i.a.i.b.s.SshTunnel(getInstance):170 - Starting connection with method: NO_TUNNEL
2023-04-23 08:03:38 [43mdestination[0m > 2023-04-23 08:03:38 [32mINFO[m c.z.h.HikariDataSource(<init>):80 - HikariPool-1 - Starting...
2023-04-23 08:03:38 [43mdestination[0m > 2023-04-23 08:03:38 [32mINFO[m c.z.h.HikariDataSource(<init>):82 - HikariPool-1 - Start completed.
2023-04-23 08:03:38 [43mdestination[0m > 2023-04-23 08:03:38 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):98 - Write config: WriteConfig{streamName=api_data, namespace=null, outputSchemaName=api, tmpTableName=_airbyte_tmp_npr_api_data, outputTableName=_airbyte_raw_api_data, syncMode=overwrite}
2023-04-23 08:03:38 [43mdestination[0m > 2023-04-23 08:03:38 [32mINFO[m i.a.i.d.b.BufferedStreamConsumer(startTracked):116 - class io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer started.
2023-04-23 08:03:38 [43mdestination[0m > 2023-04-23 08:03:38 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):123 - Preparing tmp tables in destination started for 1 streams
2023-04-23 08:03:38 [43mdestination[0m > 2023-04-23 08:03:38 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):127 - Preparing tmp table in destination started for stream api_data. schema: api, tmp table name: _airbyte_tmp_npr_api_data
2023-04-23 08:03:38 [43mdestination[0m > 2023-04-23 08:03:38 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):133 - Preparing tables in destination completed.
2023-04-23 08:03:40 [44msource[0m > Syncing stream: api_data 
2023-04-23 08:03:41 [44msource[0m > Encountered an exception while reading stream api_data
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 116, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 185, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 304, in _read_full_refresh
    message = self._get_message(record_data_or_message, stream_instance)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 338, in _get_message
    return stream_data_to_airbyte_message(stream.name, record_data_or_message, stream.transformer, stream.get_json_schema())
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/record_helper.py", line 38, in stream_data_to_airbyte_message
    raise ValueError(f"Unexpected type for data_or_message: {type(data_or_message)}: {data_or_message}")
ValueError: Unexpected type for data_or_message: <class 'str'>: offset
2023-04-23 08:03:41 [44msource[0m > Finished syncing api_data
2023-04-23 08:03:41 [44msource[0m > SourceCustomizeAPI runtimes:
Syncing stream api_data 0:00:01.683912
2023-04-23 08:03:41 [44msource[0m > Unexpected type for data_or_message: <class 'str'>: offset
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 131, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 122, in run
    for message in generator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 130, in read
    raise e
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 116, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 185, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 304, in _read_full_refresh
    message = self._get_message(record_data_or_message, stream_instance)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 338, in _get_message
    return stream_data_to_airbyte_message(stream.name, record_data_or_message, stream.transformer, stream.get_json_schema())
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/record_helper.py", line 38, in stream_data_to_airbyte_message
    raise ValueError(f"Unexpected type for data_or_message: {type(data_or_message)}: {data_or_message}")
ValueError: Unexpected type for data_or_message: <class 'str'>: offset
2023-04-23 08:03:41 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$readFromSrcAndWriteToDstRunnable$8):438 - Source has no more messages, closing connection.
2023-04-23 08:03:41 [43mdestination[0m > 2023-04-23 08:03:41 [32mINFO[m i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):65 - Airbyte message consumer: succeeded.
2023-04-23 08:03:41 [43mdestination[0m > 2023-04-23 08:03:41 [32mINFO[m i.a.i.d.b.BufferedStreamConsumer(close):171 - executing on success close procedure.
2023-04-23 08:03:41 [43mdestination[0m > 2023-04-23 08:03:41 [32mINFO[m i.a.i.d.j.SqlOperations(onDestinationCloseOperations):138 - No onDestinationCloseOperations required for this destination.
2023-04-23 08:03:41 [43mdestination[0m > 2023-04-23 08:03:41 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):163 - Finalizing tables in destination started for 1 streams
2023-04-23 08:03:41 [43mdestination[0m > 2023-04-23 08:03:41 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):168 - Finalizing stream api_data. schema api, tmp table _airbyte_tmp_npr_api_data, final table _airbyte_raw_api_data
2023-04-23 08:03:41 [43mdestination[0m > 2023-04-23 08:03:41 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):181 - Executing finalization of tables.
2023-04-23 08:03:41 [43mdestination[0m > 2023-04-23 08:03:41 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):183 - Finalizing tables in destination completed.
2023-04-23 08:03:41 [43mdestination[0m > 2023-04-23 08:03:41 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):186 - Cleaning tmp tables in destination started for 1 streams
2023-04-23 08:03:41 [43mdestination[0m > 2023-04-23 08:03:41 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):190 - Cleaning tmp table in destination started for stream api_data. schema api, tmp table name: _airbyte_tmp_npr_api_data
2023-04-23 08:03:41 [43mdestination[0m > 2023-04-23 08:03:41 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):195 - Cleaning tmp tables in destination completed.
2023-04-23 08:03:42 [43mdestination[0m > 2023-04-23 08:03:41 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):171 - Completed integration: io.airbyte.integrations.base.ssh.SshWrappedDestination
2023-04-23 08:03:42 [43mdestination[0m > 2023-04-23 08:03:41 [32mINFO[m i.a.i.d.m.MySQLDestination(main):138 - completed destination: class io.airbyte.integrations.destination.mysql.MySQLDestination
2023-04-23 08:03:42 [1;31mERROR[m i.a.w.g.DefaultReplicationWorker(replicate):278 - Sync worker failed.
io.airbyte.workers.internal.exception.SourceException: Source didn't exit properly - check the logs!
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:442) ~[io.airbyte-airbyte-commons-worker-0.44.1.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
	Suppressed: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
		at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:150) ~[io.airbyte-airbyte-commons-worker-0.44.1.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.replicate(DefaultReplicationWorker.java:214) ~[io.airbyte-airbyte-commons-worker-0.44.1.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:190) ~[io.airbyte-airbyte-commons-worker-0.44.1.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:91) ~[io.airbyte-airbyte-commons-worker-0.44.1.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$5(TemporalAttemptExecution.java:195) ~[io.airbyte-airbyte-workers-0.44.1.jar:?]
		at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
	at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:150) ~[io.airbyte-airbyte-commons-worker-0.44.1.jar:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:440) ~[io.airbyte-airbyte-commons-worker-0.44.1.jar:?]
	... 4 more
2023-04-23 08:03:42 [32mINFO[m i.a.w.g.DefaultReplicationWorker(getReplicationOutput):561 - sync summary: {
  "status" : "failed",
  "recordsSynced" : 0,
  "bytesSynced" : 0,
  "startTime" : 1682237017454,
  "endTime" : 1682237022094,
  "totalStats" : {
    "bytesCommitted" : 0,
    "bytesEmitted" : 0,
    "destinationStateMessagesEmitted" : 0,
    "destinationWriteEndTime" : 1682237022093,
    "destinationWriteStartTime" : 1682237017561,
    "meanSecondsBeforeSourceStateMessageEmitted" : 0,
    "maxSecondsBeforeSourceStateMessageEmitted" : 0,
    "maxSecondsBetweenStateMessageEmittedandCommitted" : 0,
    "meanSecondsBetweenStateMessageEmittedandCommitted" : 0,
    "recordsEmitted" : 0,
    "recordsCommitted" : 0,
    "replicationEndTime" : 1682237022094,
    "replicationStartTime" : 1682237017454,
    "sourceReadEndTime" : 0,
    "sourceReadStartTime" : 1682237017518,
    "sourceStateMessagesEmitted" : 0
  },
  "streamStats" : [ ]
}
2023-04-23 08:03:42 [32mINFO[m i.a.w.g.DefaultReplicationWorker(getReplicationOutput):562 - failures: [ {
  "failureOrigin" : "source",
  "failureType" : "system_error",
  "internalMessage" : "Unexpected type for data_or_message: <class 'str'>: offset",
  "externalMessage" : "Something went wrong in the connector. See the logs for more details.",
  "metadata" : {
    "attemptNumber" : 1,
    "jobId" : 1,
    "from_trace_message" : true,
    "connector_command" : "read"
  },
  "stacktrace" : "Traceback (most recent call last):\n  File \"/airbyte/integration_code/main.py\", line 13, in <module>\n    launch(source, sys.argv[1:])\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\", line 131, in launch\n    for message in source_entrypoint.run(parsed_args):\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\", line 122, in run\n    for message in generator:\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 130, in read\n    raise e\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 116, in read\n    yield from self._read_stream(\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 185, in _read_stream\n    for record in record_iterator:\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 304, in _read_full_refresh\n    message = self._get_message(record_data_or_message, stream_instance)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 338, in _get_message\n    return stream_data_to_airbyte_message(stream.name, record_data_or_message, stream.transformer, stream.get_json_schema())\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/record_helper.py\", line 38, in stream_data_to_airbyte_message\n    raise ValueError(f\"Unexpected type for data_or_message: {type(data_or_message)}: {data_or_message}\")\nValueError: Unexpected type for data_or_message: <class 'str'>: offset\n",
  "timestamp" : 1682237021794
}, {
  "failureOrigin" : "source",
  "internalMessage" : "Source didn't exit properly - check the logs!",
  "externalMessage" : "Something went wrong within the source connector",
  "metadata" : {
    "attemptNumber" : 1,
    "jobId" : 1,
    "connector_command" : "read"
  },
  "stacktrace" : "io.airbyte.workers.internal.exception.SourceException: Source didn't exit properly - check the logs!\n\tat io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:442)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1589)\nCaused by: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.\n\tat io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:150)\n\tat io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:440)\n\t... 4 more\n",
  "timestamp" : 1682237021924
} ]
2023-04-23 08:03:42 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):163 - Stopping cancellation check scheduling...
2023-04-23 08:03:42 [32mINFO[m i.a.w.t.s.ReplicationActivityImpl(lambda$replicate$3):157 - sync summary: io.airbyte.config.StandardSyncOutput@3333fd85[standardSyncSummary=io.airbyte.config.StandardSyncSummary@48e9ed07[status=failed,recordsSynced=0,bytesSynced=0,startTime=1682237017454,endTime=1682237022094,totalStats=io.airbyte.config.SyncStats@73e645d1[bytesCommitted=0,bytesEmitted=0,destinationStateMessagesEmitted=0,destinationWriteEndTime=1682237022093,destinationWriteStartTime=1682237017561,estimatedBytes=<null>,estimatedRecords=<null>,meanSecondsBeforeSourceStateMessageEmitted=0,maxSecondsBeforeSourceStateMessageEmitted=0,maxSecondsBetweenStateMessageEmittedandCommitted=0,meanSecondsBetweenStateMessageEmittedandCommitted=0,recordsEmitted=0,recordsCommitted=0,replicationEndTime=1682237022094,replicationStartTime=1682237017454,sourceReadEndTime=0,sourceReadStartTime=1682237017518,sourceStateMessagesEmitted=0,additionalProperties={}],streamStats=[],additionalProperties={}],normalizationSummary=<null>,webhookOperationSummary=<null>,state=<null>,outputCatalog=io.airbyte.protocol.models.ConfiguredAirbyteCatalog@51b5cef5[streams=[io.airbyte.protocol.models.ConfiguredAirbyteStream@7dc6ce93[stream=io.airbyte.protocol.models.AirbyteStream@7a4085f9[name=api_data,jsonSchema={"$schema":"http://json-schema.org/draft-07/schema","type":"object","required":["url"],"properties":{"headers":{"description":"The headers for the API request, it is a json format,eg:{'Authorization':'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ1aWQi……'}","type":"object"},"http_method":{"description":"HTTP request method, the default is GET..","type":"string"},"url":{"description":"The URL for the API endpoint.","type":"string"}}},supportedSyncModes=[full_refresh],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=overwrite,primaryKey=[],additionalProperties={}]],additionalProperties={}],failures=[io.airbyte.config.FailureReason@3bc99fad[failureOrigin=source,failureType=system_error,internalMessage=Unexpected type for data_or_message: <class 'str'>: offset,externalMessage=Something went wrong in the connector. See the logs for more details.,metadata=io.airbyte.config.Metadata@44f42c47[additionalProperties={attemptNumber=1, jobId=1, from_trace_message=true, connector_command=read}],stacktrace=Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 131, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 122, in run
    for message in generator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 130, in read
    raise e
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 116, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 185, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 304, in _read_full_refresh
    message = self._get_message(record_data_or_message, stream_instance)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 338, in _get_message
    return stream_data_to_airbyte_message(stream.name, record_data_or_message, stream.transformer, stream.get_json_schema())
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/record_helper.py", line 38, in stream_data_to_airbyte_message
    raise ValueError(f"Unexpected type for data_or_message: {type(data_or_message)}: {data_or_message}")
ValueError: Unexpected type for data_or_message: <class 'str'>: offset
,retryable=<null>,timestamp=1682237021794,additionalProperties={}], io.airbyte.config.FailureReason@f8dc01c[failureOrigin=source,failureType=<null>,internalMessage=Source didn't exit properly - check the logs!,externalMessage=Something went wrong within the source connector,metadata=io.airbyte.config.Metadata@711cf359[additionalProperties={attemptNumber=1, jobId=1, connector_command=read}],stacktrace=io.airbyte.workers.internal.exception.SourceException: Source didn't exit properly - check the logs!
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:442)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
	at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:150)
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:440)
	... 4 more
,retryable=<null>,timestamp=1682237021924,additionalProperties={}]],commitStateAsap=true,additionalProperties={}]
2023-04-23 08:03:42 [32mINFO[m i.a.w.t.s.ReplicationActivityImpl(lambda$replicate$3):162 - Sync summary length: 5333
2023-04-23 08:03:42 [32mINFO[m i.a.c.t.TemporalUtils(withBackgroundHeartbeat):307 - Stopping temporal heartbeating...
2023-04-23 08:03:42 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-23 08:03:42 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- END REPLICATION -----
2023-04-23 08:03:42 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-23 08:03:46 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to Get a connection by connection Id
2023-04-23 08:03:46 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to get the most recent source actor catalog
2023-04-23 08:03:46 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to Get a connection by connection Id
2023-04-23 08:03:42 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):136 - Docker volume job log path: /tmp/workspace/1/2/logs.log
2023-04-23 08:03:42 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):141 - Executing worker wrapper. Airbyte version: 0.44.1
2023-04-23 08:03:42 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to save workflow id for cancellation
2023-04-23 08:03:42 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2023-04-23 08:03:42 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-23 08:03:42 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- START CHECK -----
2023-04-23 08:03:42 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2023-04-23 08:03:42 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-23 08:03:42 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2023-04-23 08:03:42 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2023-04-23 08:03:42 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable LAUNCHDARKLY_KEY: ''
2023-04-23 08:03:42 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable FEATURE_FLAG_CLIENT: ''
2023-04-23 08:03:42 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - Checking if airbyte/source-customize-api:0.0.12 exists...
2023-04-23 08:03:42 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - airbyte/source-customize-api:0.0.12 was found locally.
2023-04-23 08:03:42 [32mINFO[m i.a.w.p.DockerProcessFactory(create):133 - Creating docker container = source-customize-api-check-1-2-swweo with resources io.airbyte.config.ResourceRequirements@9e89d38[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts null
2023-04-23 08:03:42 [32mINFO[m i.a.w.p.DockerProcessFactory(create):184 - Preparing command: docker run --rm --init -i -w /data/1/2 --log-driver none --name source-customize-api-check-1-2-swweo --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/source-customize-api:0.0.12 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e USE_STREAM_CAPABLE_STATE=true -e FIELD_SELECTION_WORKSPACES= -e WORKER_ENVIRONMENT=DOCKER -e AIRBYTE_ROLE= -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=2 -e OTEL_COLLECTOR_ENDPOINT=http://host.docker.internal:4317 -e FEATURE_FLAG_CLIENT= -e AIRBYTE_VERSION=0.44.1 -e WORKER_JOB_ID=1 airbyte/source-customize-api:0.0.12 check --config source_config.json
2023-04-23 08:03:42 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(create):181 - Reading messages from protocol version 0.2.0
2023-04-23 08:03:43 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):317 - headers_str: { 	"Authorization": "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJTNmJDSFdHU3p1VjgtaVFZY19OdE9yUUpick54RDF2dEV4U0duOXMtMnRRIn0.eyJqdGkiOiIxN2EwY2UyMi00ZjM4LTRhOWYtODExNy1hNWZkOGVjOWZjYWQiLCJleHAiOjE2ODIzMjA3OTMsIm5iZiI6MCwiaWF0IjoxNjgyMjM0MzkzLCJpc3MiOiJodHRwczovL2JvLXRlc3Qtc3NvLmxpbmt0aW1lY2xvdWQuY29tL2F1dGgvcmVhbG1zL2Jkb3MiLCJzdWIiOiJiNGZhZjY1Yi1hNmMwLTQ2ZTEtYTYyNy1lYzJlMjU3OWZjZTciLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiZG9zLWV0bCIsImF1dGhfdGltZSI6MCwic2Vzc2lvbl9zdGF0ZSI6IjdlOWJlMmZjLTllZDQtNGFhNi1iOTMzLTBmYzVmNjhjNjY0NSIsImFjciI6IjEiLCJzY29wZSI6InByb2ZpbGUgZW1haWwiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJicmFuZG9uIGJkb3MiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJicmFuZG9uIiwiZ2l2ZW5fbmFtZSI6ImJyYW5kb24iLCJsb2NhbGUiOiJ6aC1DTiIsImZhbWlseV9uYW1lIjoiYmRvcyIsImVtYWlsIjoiYnJhbmRvbi5zdW5AbGlua3RpbWUuY2xvdWQifQ.P4iBqSIDbjv8yN7kbyGdEobQ2LWMcznMiGT-qA0hlFcd0gulN-mLal5TgBe4HQIbtGuQX1xU6M21GznAm6ZpZIyyA4YFBVnzgtkpG3V12aKotEgScgCPwgkGAj0Q4wuPoKDA6I2VMA0IzTBdP9h4ibPrb5n4n-44zm8K1JcoSl_PLC60A9ztWEEVfSpAF4lZlWINg44-ComenW5c-p7rL1nHGKmvnxlweXqFnlzZccyDFRCFWbRDr1OT7u0w2nGjme6bBqA1QEE2p-Sdq0ozNZlZ_dZFpIeCWFrar7GLvU8sYB5xp2jJFcrLibl3v_OiX6QKKeLfVT1QNsxUpiYlXA", 	"active-org": "uid=fda805d0-ba2b-11ec-b905-51d902e7b1bc;user=brandon;reqUserName=brandon;type=undefined" }...
2023-04-23 08:03:43 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):317 - body_data: {'limit': 2, 'loginUserName': 'brandon', 'user': 'brandon'}...
2023-04-23 08:03:43 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):317 - Attempting to connect to API at http://192.168.200.124:9099/project/list...
2023-04-23 08:03:43 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):317 - http method is-> POST...
2023-04-23 08:03:44 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):317 - Response from POST: http://192.168.200.124:9099/project/list: {'message': 'success', 'status': 1, 'data': {'offset': 0, 'limit': None, 'total': 74, 'list': [{'id': 2860, 'status': 0, 'sourceProjectId': None, 'name': 'python导出test_模板_1680589641748', 'desc': '', 'homepageUrl': None, 'homepageName': None, 'homepageImg': None, 'readme': None, 'openFlag': '{"tutorial":false}', 'type': 3, 'userId': 'brandon', 'groupId': '0a71e4b0-c3a1-11ec-96bd-35126eddec60', 'workflowId': None, 'cron': None, 'avatar': None, 'features': None, 'lastClickTime': '2023-04-19 14:21:05', 'createTime': '2023-04-04 14:27:24', 'updateTime': '2023-04-18 12:58:42', 'memberIds': [], 'groupIds': [], 'tags': None, 'updateUserId': 'brandon', 'starCount': 0, 'categoryId': 1, 'secondaryCategoryId': 0}, {'id': 2857, 'status': 0, 'sourceProjectId': None, 'name': 'python导出test', 'desc': '', 'homepageUrl': None, 'homepageName': None, 'homepageImg': None, 'readme': None, 'openFlag': None, 'type': 4, 'userId': 'qa25org_admin', 'groupId': '0a71e4b0-c3a1-11ec-96bd-35126eddec60', 'workflowId': None, 'cron': None, 'avatar': None, 'features': None, 'lastClickTime': '2023-04-04 09:25:57', 'createTime': '2023-04-04 09:21:42', 'updateTime': '2023-04-04 09:26:19', 'memberIds': [], 'groupIds': [], 'tags': None, 'updateUserId': 'qa25org_admin', 'starCount': 0, 'categoryId': 1, 'secondaryCategoryId': 0}]}, 'error': None}
2023-04-23 08:03:44 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):317 - Check connection status: True
2023-04-23 08:03:44 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):317 - Check connection success
2023-04-23 08:03:44 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):317 - Check succeeded
2023-04-23 08:03:44 [32mINFO[m i.a.w.g.DefaultCheckConnectionWorker(run):115 - Check connection job received output: io.airbyte.config.StandardCheckConnectionOutput@6e7bb52e[status=succeeded,message=<null>,additionalProperties={}]
2023-04-23 08:03:44 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-23 08:03:44 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- END CHECK -----
2023-04-23 08:03:44 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-23 08:03:44 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):163 - Stopping cancellation check scheduling...
2023-04-23 08:03:44 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):136 - Docker volume job log path: /tmp/workspace/1/2/logs.log
2023-04-23 08:03:44 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):141 - Executing worker wrapper. Airbyte version: 0.44.1
2023-04-23 08:03:44 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to save workflow id for cancellation
2023-04-23 08:03:44 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-23 08:03:44 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2023-04-23 08:03:44 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- START CHECK -----
2023-04-23 08:03:44 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2023-04-23 08:03:44 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-23 08:03:44 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2023-04-23 08:03:44 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2023-04-23 08:03:44 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable LAUNCHDARKLY_KEY: ''
2023-04-23 08:03:44 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable FEATURE_FLAG_CLIENT: ''
2023-04-23 08:03:44 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - Checking if airbyte/destination-mysql:0.1.20 exists...
2023-04-23 08:03:44 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - airbyte/destination-mysql:0.1.20 was found locally.
2023-04-23 08:03:44 [32mINFO[m i.a.w.p.DockerProcessFactory(create):133 - Creating docker container = destination-mysql-check-1-2-hbesr with resources io.airbyte.config.ResourceRequirements@9e89d38[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts null
2023-04-23 08:03:44 [32mINFO[m i.a.w.p.DockerProcessFactory(create):184 - Preparing command: docker run --rm --init -i -w /data/1/2 --log-driver none --name destination-mysql-check-1-2-hbesr --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/destination-mysql:0.1.20 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e USE_STREAM_CAPABLE_STATE=true -e FIELD_SELECTION_WORKSPACES= -e WORKER_ENVIRONMENT=DOCKER -e AIRBYTE_ROLE= -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=2 -e OTEL_COLLECTOR_ENDPOINT=http://host.docker.internal:4317 -e FEATURE_FLAG_CLIENT= -e AIRBYTE_VERSION=0.44.1 -e WORKER_JOB_ID=1 airbyte/destination-mysql:0.1.20 check --config source_config.json
2023-04-23 08:03:44 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(create):181 - Reading messages from protocol version 0.2.0
2023-04-23 08:03:45 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):149 - SLF4J: Class path contains multiple SLF4J bindings.
2023-04-23 08:03:45 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):149 - SLF4J: Found binding in [jar:file:/airbyte/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-04-23 08:03:45 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):149 - SLF4J: Found binding in [jar:file:/airbyte/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-04-23 08:03:45 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):149 - SLF4J: Found binding in [jar:file:/airbyte/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-04-23 08:03:45 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):149 - SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
2023-04-23 08:03:45 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):149 - SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
2023-04-23 08:03:45 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:45 [32mINFO[m i.a.i.d.m.MySQLDestination(main):136 - starting destination: class io.airbyte.integrations.destination.mysql.MySQLDestination
2023-04-23 08:03:45 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:45 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):118 - integration args: {check=null, config=source_config.json}
2023-04-23 08:03:45 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:45 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):123 - Running integration: io.airbyte.integrations.base.ssh.SshWrappedDestination
2023-04-23 08:03:45 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:45 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):124 - Command: CHECK
2023-04-23 08:03:45 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:45 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):125 - Integration config: IntegrationConfig{command=CHECK, configPath='source_config.json', catalogPath='null', statePath='null'}
2023-04-23 08:03:45 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:45 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-04-23 08:03:45 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:45 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword examples - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-04-23 08:03:45 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:45 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-04-23 08:03:45 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:45 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword multiline - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-04-23 08:03:45 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:45 [32mINFO[m i.a.i.b.s.SshTunnel(getInstance):170 - Starting connection with method: NO_TUNNEL
2023-04-23 08:03:45 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:45 [32mINFO[m c.z.h.HikariDataSource(<init>):80 - HikariPool-1 - Starting...
2023-04-23 08:03:45 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:45 [32mINFO[m c.z.h.HikariDataSource(<init>):82 - HikariPool-1 - Start completed.
2023-04-23 08:03:46 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:46 [32mINFO[m c.z.h.HikariDataSource(close):350 - HikariPool-1 - Shutdown initiated...
2023-04-23 08:03:46 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:46 [32mINFO[m c.z.h.HikariDataSource(close):352 - HikariPool-1 - Shutdown completed.
2023-04-23 08:03:46 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:46 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):171 - Completed integration: io.airbyte.integrations.base.ssh.SshWrappedDestination
2023-04-23 08:03:46 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):369 - 2023-04-23 08:03:46 [32mINFO[m i.a.i.d.m.MySQLDestination(main):138 - completed destination: class io.airbyte.integrations.destination.mysql.MySQLDestination
2023-04-23 08:03:46 [32mINFO[m i.a.w.g.DefaultCheckConnectionWorker(run):115 - Check connection job received output: io.airbyte.config.StandardCheckConnectionOutput@1878f77e[status=succeeded,message=<null>,additionalProperties={}]
2023-04-23 08:03:46 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-23 08:03:46 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- END CHECK -----
2023-04-23 08:03:46 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-23 08:03:46 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):163 - Stopping cancellation check scheduling...
2023-04-23 08:03:46 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to get state
2023-04-23 08:03:46 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to set attempt sync config
2023-04-23 08:03:46 [32mINFO[m i.a.c.t.s.DefaultTaskQueueMapper(getTaskQueue):31 - Called DefaultTaskQueueMapper getTaskQueue for geography auto
2023-04-23 08:03:46 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):136 - Docker volume job log path: /tmp/workspace/1/2/logs.log
2023-04-23 08:03:46 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):141 - Executing worker wrapper. Airbyte version: 0.44.1
2023-04-23 08:03:46 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to save workflow id for cancellation
2023-04-23 08:03:46 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to get the source for heartbeat
2023-04-23 08:03:46 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to get the source definition
2023-04-23 08:03:46 [32mINFO[m i.a.w.g.ReplicationWorkerFactory(create):95 - Setting up source...
2023-04-23 08:03:46 [32mINFO[m i.a.w.g.ReplicationWorkerFactory(create):99 - Setting up destination...
2023-04-23 08:03:46 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable METRIC_CLIENT: ''
2023-04-23 08:03:46 [33mWARN[m i.a.m.l.MetricClientFactory(initialize):60 - Metric client is already initialized to 
2023-04-23 08:03:46 [32mINFO[m i.a.w.g.ReplicationWorkerFactory(create):108 - Setting up replication worker...
2023-04-23 08:03:46 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):161 - start sync worker. job id: 1 attempt id: 2
2023-04-23 08:03:46 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):163 - Committing states from replication activity
2023-04-23 08:03:46 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):166 - Committing stats from replication activity
2023-04-23 08:03:46 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):182 - configured sync modes: {null.api_data=full_refresh - overwrite}
2023-04-23 08:03:46 [32mINFO[m i.a.w.i.DefaultAirbyteDestination(start):92 - Running destination...
2023-04-23 08:03:46 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2023-04-23 08:03:46 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2023-04-23 08:03:46 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2023-04-23 08:03:46 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2023-04-23 08:03:46 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable LAUNCHDARKLY_KEY: ''
2023-04-23 08:03:46 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable FEATURE_FLAG_CLIENT: ''
2023-04-23 08:03:46 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-23 08:03:46 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- START REPLICATION -----
2023-04-23 08:03:46 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-23 08:03:46 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - Checking if airbyte/destination-mysql:0.1.20 exists...
2023-04-23 08:03:46 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - airbyte/destination-mysql:0.1.20 was found locally.
2023-04-23 08:03:46 [32mINFO[m i.a.w.p.DockerProcessFactory(create):133 - Creating docker container = destination-mysql-write-1-2-eoavh with resources io.airbyte.config.ResourceRequirements@3267ab7a[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts null
2023-04-23 08:03:46 [32mINFO[m i.a.w.p.DockerProcessFactory(create):184 - Preparing command: docker run --rm --init -i -w /data/1/2 --log-driver none --name destination-mysql-write-1-2-eoavh --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/destination-mysql:0.1.20 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e USE_STREAM_CAPABLE_STATE=true -e FIELD_SELECTION_WORKSPACES= -e WORKER_ENVIRONMENT=DOCKER -e AIRBYTE_ROLE= -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=2 -e OTEL_COLLECTOR_ENDPOINT=http://host.docker.internal:4317 -e FEATURE_FLAG_CLIENT= -e AIRBYTE_VERSION=0.44.1 -e WORKER_JOB_ID=1 airbyte/destination-mysql:0.1.20 write --config destination_config.json --catalog destination_catalog.json
2023-04-23 08:03:46 [32mINFO[m i.a.w.i.VersionedAirbyteMessageBufferedWriterFactory(createWriter):41 - Writing messages to protocol version 0.2.0
2023-04-23 08:03:46 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(create):181 - Reading messages from protocol version 0.2.0
2023-04-23 08:03:46 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2023-04-23 08:03:46 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2023-04-23 08:03:46 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2023-04-23 08:03:46 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2023-04-23 08:03:46 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable LAUNCHDARKLY_KEY: ''
2023-04-23 08:03:46 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable FEATURE_FLAG_CLIENT: ''
2023-04-23 08:03:46 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - Checking if airbyte/source-customize-api:0.0.12 exists...
2023-04-23 08:03:46 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - airbyte/source-customize-api:0.0.12 was found locally.
2023-04-23 08:03:46 [32mINFO[m i.a.w.p.DockerProcessFactory(create):133 - Creating docker container = source-customize-api-read-1-2-iszad with resources io.airbyte.config.ResourceRequirements@50ae68d6[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts null
2023-04-23 08:03:46 [32mINFO[m i.a.w.p.DockerProcessFactory(create):184 - Preparing command: docker run --rm --init -i -w /data/1/2 --log-driver none --name source-customize-api-read-1-2-iszad --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/source-customize-api:0.0.12 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e USE_STREAM_CAPABLE_STATE=true -e FIELD_SELECTION_WORKSPACES= -e WORKER_ENVIRONMENT=DOCKER -e AIRBYTE_ROLE= -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=2 -e OTEL_COLLECTOR_ENDPOINT=http://host.docker.internal:4317 -e FEATURE_FLAG_CLIENT= -e AIRBYTE_VERSION=0.44.1 -e WORKER_JOB_ID=1 airbyte/source-customize-api:0.0.12 read --config source_config.json --catalog source_catalog.json
2023-04-23 08:03:46 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(create):181 - Reading messages from protocol version 0.2.0
2023-04-23 08:03:46 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$readFromDstRunnable$4):310 - Destination output thread started.
2023-04-23 08:03:46 [32mINFO[m i.a.w.i.HeartbeatTimeoutChaperone(runWithHeartbeatThread):94 - Starting source heartbeat check. Will check every 1 minutes.
2023-04-23 08:03:46 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$readFromSrcAndWriteToDstRunnable$8):376 - Replication thread started.
2023-04-23 08:03:47 [43mdestination[0m > SLF4J: Class path contains multiple SLF4J bindings.
2023-04-23 08:03:47 [43mdestination[0m > SLF4J: Found binding in [jar:file:/airbyte/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-04-23 08:03:47 [43mdestination[0m > SLF4J: Found binding in [jar:file:/airbyte/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-04-23 08:03:47 [43mdestination[0m > SLF4J: Found binding in [jar:file:/airbyte/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-04-23 08:03:47 [43mdestination[0m > SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
2023-04-23 08:03:47 [43mdestination[0m > SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
2023-04-23 08:03:47 [43mdestination[0m > 2023-04-23 08:03:47 [32mINFO[m i.a.i.d.m.MySQLDestination(main):136 - starting destination: class io.airbyte.integrations.destination.mysql.MySQLDestination
2023-04-23 08:03:47 [43mdestination[0m > 2023-04-23 08:03:47 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):118 - integration args: {catalog=destination_catalog.json, write=null, config=destination_config.json}
2023-04-23 08:03:47 [43mdestination[0m > 2023-04-23 08:03:47 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):123 - Running integration: io.airbyte.integrations.base.ssh.SshWrappedDestination
2023-04-23 08:03:47 [43mdestination[0m > 2023-04-23 08:03:47 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):124 - Command: WRITE
2023-04-23 08:03:47 [43mdestination[0m > 2023-04-23 08:03:47 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):125 - Integration config: IntegrationConfig{command=WRITE, configPath='destination_config.json', catalogPath='destination_catalog.json', statePath='null'}
2023-04-23 08:03:47 [43mdestination[0m > 2023-04-23 08:03:47 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-04-23 08:03:47 [43mdestination[0m > 2023-04-23 08:03:47 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword examples - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-04-23 08:03:47 [43mdestination[0m > 2023-04-23 08:03:47 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-04-23 08:03:47 [43mdestination[0m > 2023-04-23 08:03:47 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword multiline - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-04-23 08:03:47 [44msource[0m > Starting syncing SourceCustomizeAPI
2023-04-23 08:03:47 [43mdestination[0m > 2023-04-23 08:03:47 [32mINFO[m i.a.i.b.s.SshTunnel(getInstance):170 - Starting connection with method: NO_TUNNEL
2023-04-23 08:03:47 [43mdestination[0m > 2023-04-23 08:03:47 [32mINFO[m c.z.h.HikariDataSource(<init>):80 - HikariPool-1 - Starting...
2023-04-23 08:03:47 [43mdestination[0m > 2023-04-23 08:03:47 [32mINFO[m c.z.h.HikariDataSource(<init>):82 - HikariPool-1 - Start completed.
2023-04-23 08:03:47 [43mdestination[0m > 2023-04-23 08:03:47 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):98 - Write config: WriteConfig{streamName=api_data, namespace=null, outputSchemaName=api, tmpTableName=_airbyte_tmp_mbm_api_data, outputTableName=_airbyte_raw_api_data, syncMode=overwrite}
2023-04-23 08:03:47 [43mdestination[0m > 2023-04-23 08:03:47 [32mINFO[m i.a.i.d.b.BufferedStreamConsumer(startTracked):116 - class io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer started.
2023-04-23 08:03:47 [43mdestination[0m > 2023-04-23 08:03:47 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):123 - Preparing tmp tables in destination started for 1 streams
2023-04-23 08:03:47 [43mdestination[0m > 2023-04-23 08:03:47 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):127 - Preparing tmp table in destination started for stream api_data. schema: api, tmp table name: _airbyte_tmp_mbm_api_data
2023-04-23 08:03:48 [43mdestination[0m > 2023-04-23 08:03:48 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):133 - Preparing tables in destination completed.
2023-04-23 08:03:48 [44msource[0m > Syncing stream: api_data 
2023-04-23 08:03:48 [44msource[0m > Encountered an exception while reading stream api_data
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 116, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 185, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 304, in _read_full_refresh
    message = self._get_message(record_data_or_message, stream_instance)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 338, in _get_message
    return stream_data_to_airbyte_message(stream.name, record_data_or_message, stream.transformer, stream.get_json_schema())
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/record_helper.py", line 38, in stream_data_to_airbyte_message
    raise ValueError(f"Unexpected type for data_or_message: {type(data_or_message)}: {data_or_message}")
ValueError: Unexpected type for data_or_message: <class 'str'>: offset
2023-04-23 08:03:49 [44msource[0m > Finished syncing api_data
2023-04-23 08:03:49 [44msource[0m > SourceCustomizeAPI runtimes:
Syncing stream api_data 0:00:00.576143
2023-04-23 08:03:49 [44msource[0m > Unexpected type for data_or_message: <class 'str'>: offset
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 131, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 122, in run
    for message in generator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 130, in read
    raise e
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 116, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 185, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 304, in _read_full_refresh
    message = self._get_message(record_data_or_message, stream_instance)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 338, in _get_message
    return stream_data_to_airbyte_message(stream.name, record_data_or_message, stream.transformer, stream.get_json_schema())
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/record_helper.py", line 38, in stream_data_to_airbyte_message
    raise ValueError(f"Unexpected type for data_or_message: {type(data_or_message)}: {data_or_message}")
ValueError: Unexpected type for data_or_message: <class 'str'>: offset
2023-04-23 08:03:49 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$readFromSrcAndWriteToDstRunnable$8):438 - Source has no more messages, closing connection.
2023-04-23 08:03:49 [43mdestination[0m > 2023-04-23 08:03:49 [32mINFO[m i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):65 - Airbyte message consumer: succeeded.
2023-04-23 08:03:49 [43mdestination[0m > 2023-04-23 08:03:49 [32mINFO[m i.a.i.d.b.BufferedStreamConsumer(close):171 - executing on success close procedure.
2023-04-23 08:03:49 [43mdestination[0m > 2023-04-23 08:03:49 [32mINFO[m i.a.i.d.j.SqlOperations(onDestinationCloseOperations):138 - No onDestinationCloseOperations required for this destination.
2023-04-23 08:03:49 [43mdestination[0m > 2023-04-23 08:03:49 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):163 - Finalizing tables in destination started for 1 streams
2023-04-23 08:03:49 [43mdestination[0m > 2023-04-23 08:03:49 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):168 - Finalizing stream api_data. schema api, tmp table _airbyte_tmp_mbm_api_data, final table _airbyte_raw_api_data
2023-04-23 08:03:49 [43mdestination[0m > 2023-04-23 08:03:49 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):181 - Executing finalization of tables.
2023-04-23 08:03:49 [43mdestination[0m > 2023-04-23 08:03:49 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):183 - Finalizing tables in destination completed.
2023-04-23 08:03:49 [43mdestination[0m > 2023-04-23 08:03:49 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):186 - Cleaning tmp tables in destination started for 1 streams
2023-04-23 08:03:49 [43mdestination[0m > 2023-04-23 08:03:49 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):190 - Cleaning tmp table in destination started for stream api_data. schema api, tmp table name: _airbyte_tmp_mbm_api_data
2023-04-23 08:03:49 [43mdestination[0m > 2023-04-23 08:03:49 [32mINFO[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):195 - Cleaning tmp tables in destination completed.
2023-04-23 08:03:49 [43mdestination[0m > 2023-04-23 08:03:49 [32mINFO[m i.a.i.b.IntegrationRunner(runInternal):171 - Completed integration: io.airbyte.integrations.base.ssh.SshWrappedDestination
2023-04-23 08:03:49 [43mdestination[0m > 2023-04-23 08:03:49 [32mINFO[m i.a.i.d.m.MySQLDestination(main):138 - completed destination: class io.airbyte.integrations.destination.mysql.MySQLDestination
2023-04-23 08:03:49 [1;31mERROR[m i.a.w.g.DefaultReplicationWorker(replicate):278 - Sync worker failed.
io.airbyte.workers.internal.exception.SourceException: Source didn't exit properly - check the logs!
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:442) ~[io.airbyte-airbyte-commons-worker-0.44.1.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
	Suppressed: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
		at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:150) ~[io.airbyte-airbyte-commons-worker-0.44.1.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.replicate(DefaultReplicationWorker.java:214) ~[io.airbyte-airbyte-commons-worker-0.44.1.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:190) ~[io.airbyte-airbyte-commons-worker-0.44.1.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:91) ~[io.airbyte-airbyte-commons-worker-0.44.1.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$5(TemporalAttemptExecution.java:195) ~[io.airbyte-airbyte-workers-0.44.1.jar:?]
		at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
	at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:150) ~[io.airbyte-airbyte-commons-worker-0.44.1.jar:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:440) ~[io.airbyte-airbyte-commons-worker-0.44.1.jar:?]
	... 4 more
2023-04-23 08:03:49 [32mINFO[m i.a.w.g.DefaultReplicationWorker(getReplicationOutput):561 - sync summary: {
  "status" : "failed",
  "recordsSynced" : 0,
  "bytesSynced" : 0,
  "startTime" : 1682237026650,
  "endTime" : 1682237029357,
  "totalStats" : {
    "bytesCommitted" : 0,
    "bytesEmitted" : 0,
    "destinationStateMessagesEmitted" : 0,
    "destinationWriteEndTime" : 0,
    "destinationWriteStartTime" : 1682237026763,
    "meanSecondsBeforeSourceStateMessageEmitted" : 0,
    "maxSecondsBeforeSourceStateMessageEmitted" : 0,
    "maxSecondsBetweenStateMessageEmittedandCommitted" : 0,
    "meanSecondsBetweenStateMessageEmittedandCommitted" : 0,
    "recordsEmitted" : 0,
    "recordsCommitted" : 0,
    "replicationEndTime" : 1682237029357,
    "replicationStartTime" : 1682237026650,
    "sourceReadEndTime" : 0,
    "sourceReadStartTime" : 1682237026707,
    "sourceStateMessagesEmitted" : 0
  },
  "streamStats" : [ ]
}
2023-04-23 08:03:49 [32mINFO[m i.a.w.g.DefaultReplicationWorker(getReplicationOutput):562 - failures: [ {
  "failureOrigin" : "source",
  "failureType" : "system_error",
  "internalMessage" : "Unexpected type for data_or_message: <class 'str'>: offset",
  "externalMessage" : "Something went wrong in the connector. See the logs for more details.",
  "metadata" : {
    "attemptNumber" : 2,
    "jobId" : 1,
    "from_trace_message" : true,
    "connector_command" : "read"
  },
  "stacktrace" : "Traceback (most recent call last):\n  File \"/airbyte/integration_code/main.py\", line 13, in <module>\n    launch(source, sys.argv[1:])\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\", line 131, in launch\n    for message in source_entrypoint.run(parsed_args):\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\", line 122, in run\n    for message in generator:\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 130, in read\n    raise e\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 116, in read\n    yield from self._read_stream(\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 185, in _read_stream\n    for record in record_iterator:\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 304, in _read_full_refresh\n    message = self._get_message(record_data_or_message, stream_instance)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 338, in _get_message\n    return stream_data_to_airbyte_message(stream.name, record_data_or_message, stream.transformer, stream.get_json_schema())\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/record_helper.py\", line 38, in stream_data_to_airbyte_message\n    raise ValueError(f\"Unexpected type for data_or_message: {type(data_or_message)}: {data_or_message}\")\nValueError: Unexpected type for data_or_message: <class 'str'>: offset\n",
  "timestamp" : 1682237028999
}, {
  "failureOrigin" : "source",
  "internalMessage" : "Source didn't exit properly - check the logs!",
  "externalMessage" : "Something went wrong within the source connector",
  "metadata" : {
    "attemptNumber" : 2,
    "jobId" : 1,
    "connector_command" : "read"
  },
  "stacktrace" : "io.airbyte.workers.internal.exception.SourceException: Source didn't exit properly - check the logs!\n\tat io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:442)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1589)\nCaused by: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.\n\tat io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:150)\n\tat io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:440)\n\t... 4 more\n",
  "timestamp" : 1682237029179
} ]
2023-04-23 08:03:49 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):163 - Stopping cancellation check scheduling...
2023-04-23 08:03:49 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-23 08:03:49 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- END REPLICATION -----
2023-04-23 08:03:49 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-23 08:03:49 [32mINFO[m i.a.w.t.s.ReplicationActivityImpl(lambda$replicate$3):157 - sync summary: io.airbyte.config.StandardSyncOutput@6db19cd0[standardSyncSummary=io.airbyte.config.StandardSyncSummary@5981228a[status=failed,recordsSynced=0,bytesSynced=0,startTime=1682237026650,endTime=1682237029357,totalStats=io.airbyte.config.SyncStats@d4919ad[bytesCommitted=0,bytesEmitted=0,destinationStateMessagesEmitted=0,destinationWriteEndTime=0,destinationWriteStartTime=1682237026763,estimatedBytes=<null>,estimatedRecords=<null>,meanSecondsBeforeSourceStateMessageEmitted=0,maxSecondsBeforeSourceStateMessageEmitted=0,maxSecondsBetweenStateMessageEmittedandCommitted=0,meanSecondsBetweenStateMessageEmittedandCommitted=0,recordsEmitted=0,recordsCommitted=0,replicationEndTime=1682237029357,replicationStartTime=1682237026650,sourceReadEndTime=0,sourceReadStartTime=1682237026707,sourceStateMessagesEmitted=0,additionalProperties={}],streamStats=[],additionalProperties={}],normalizationSummary=<null>,webhookOperationSummary=<null>,state=<null>,outputCatalog=io.airbyte.protocol.models.ConfiguredAirbyteCatalog@78314069[streams=[io.airbyte.protocol.models.ConfiguredAirbyteStream@198704a3[stream=io.airbyte.protocol.models.AirbyteStream@49c2f06b[name=api_data,jsonSchema={"$schema":"http://json-schema.org/draft-07/schema","type":"object","required":["url"],"properties":{"headers":{"description":"The headers for the API request, it is a json format,eg:{'Authorization':'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ1aWQi……'}","type":"object"},"http_method":{"description":"HTTP request method, the default is GET..","type":"string"},"url":{"description":"The URL for the API endpoint.","type":"string"}}},supportedSyncModes=[full_refresh],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=overwrite,primaryKey=[],additionalProperties={}]],additionalProperties={}],failures=[io.airbyte.config.FailureReason@c030c8f[failureOrigin=source,failureType=system_error,internalMessage=Unexpected type for data_or_message: <class 'str'>: offset,externalMessage=Something went wrong in the connector. See the logs for more details.,metadata=io.airbyte.config.Metadata@7ec3376e[additionalProperties={attemptNumber=2, jobId=1, from_trace_message=true, connector_command=read}],stacktrace=Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 131, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 122, in run
    for message in generator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 130, in read
    raise e
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 116, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 185, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 304, in _read_full_refresh
    message = self._get_message(record_data_or_message, stream_instance)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 338, in _get_message
    return stream_data_to_airbyte_message(stream.name, record_data_or_message, stream.transformer, stream.get_json_schema())
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/record_helper.py", line 38, in stream_data_to_airbyte_message
    raise ValueError(f"Unexpected type for data_or_message: {type(data_or_message)}: {data_or_message}")
ValueError: Unexpected type for data_or_message: <class 'str'>: offset
,retryable=<null>,timestamp=1682237028999,additionalProperties={}], io.airbyte.config.FailureReason@5fc09609[failureOrigin=source,failureType=<null>,internalMessage=Source didn't exit properly - check the logs!,externalMessage=Something went wrong within the source connector,metadata=io.airbyte.config.Metadata@1df7432[additionalProperties={attemptNumber=2, jobId=1, connector_command=read}],stacktrace=io.airbyte.workers.internal.exception.SourceException: Source didn't exit properly - check the logs!
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:442)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
	at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:150)
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:440)
	... 4 more
,retryable=<null>,timestamp=1682237029179,additionalProperties={}]],commitStateAsap=true,additionalProperties={}]
2023-04-23 08:03:49 [32mINFO[m i.a.w.t.s.ReplicationActivityImpl(lambda$replicate$3):162 - Sync summary length: 5319
2023-04-23 08:03:49 [32mINFO[m i.a.c.t.TemporalUtils(withBackgroundHeartbeat):307 - Stopping temporal heartbeating...
2023-04-23 08:03:49 [32mINFO[m i.a.p.j.e.LoggingJobErrorReportingClient(reportJobFailureReason):26 - Report Job Error -> workspaceId: 1fa5b3ad-8181-444f-8ce1-a4466b7c4a34, dockerImage: airbyte/source-customize-api:0.0.12, failureReason: io.airbyte.config.FailureReason@598ad486[failureOrigin=source,failureType=system_error,internalMessage=Unexpected type for data_or_message: <class 'str'>: offset,externalMessage=Something went wrong in the connector. See the logs for more details.,metadata=io.airbyte.config.Metadata@2d525649[additionalProperties={attemptNumber=2, jobId=1, connector_command=read, from_trace_message=true}],stacktrace=Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 131, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 122, in run
    for message in generator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 130, in read
    raise e
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 116, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 185, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 304, in _read_full_refresh
    message = self._get_message(record_data_or_message, stream_instance)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 338, in _get_message
    return stream_data_to_airbyte_message(stream.name, record_data_or_message, stream.transformer, stream.get_json_schema())
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/record_helper.py", line 38, in stream_data_to_airbyte_message
    raise ValueError(f"Unexpected type for data_or_message: {type(data_or_message)}: {data_or_message}")
ValueError: Unexpected type for data_or_message: <class 'str'>: offset
,retryable=<null>,timestamp=1682237028999,additionalProperties={}], metadata: {connector_repository=airbyte/source-customize-api, workspace_url=http://localhost:8000/workspaces/1fa5b3ad-8181-444f-8ce1-a4466b7c4a34, failure_type=system_error, connector_command=read, connector_name=api 12, workspace_id=1fa5b3ad-8181-444f-8ce1-a4466b7c4a34, airbyte_version=0.44.1, connection_url=http://localhost:8000/workspaces/1fa5b3ad-8181-444f-8ce1-a4466b7c4a34/connections/a55c17b6-00d2-436a-82d9-d2cec4cce0be, connector_definition_id=0c9b274b-35a2-4988-8610-47232e46cdfb, failure_origin=source, connection_id=a55c17b6-00d2-436a-82d9-d2cec4cce0be, connector_release_stage=custom, job_id=1, deployment_mode=OSS}
2023-04-23 08:03:49 [33mWARN[m c.n.s.JsonMetaSchema(newValidator):278 - Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
2023-04-23 08:03:49 [32mINFO[m i.a.c.f.EnvVariableFeatureFlags(autoDisablesFailingConnections):36 - Auto Disable Failing Connections: false